### ISSUE TITLE
(Modded) Pawn/Animal Ticking errors

### ISSUE THREAD

**Issue by LuzBun** [rwmt/Multiplayer#227]
Upon hosting a game with my personal pack that was stable in 1.2 (it's in collections if you need it to test), pretty much every AI on the map throw an error resulting in any clients desyncing instantly and my log being spammed at a rate fast enough to kill performance. Attached is the Host player log, the Client player log, and the client desync file.
[Host Player Log.log](https://github.com/rwmt/Multiplayer/files/6920168/Host.Player.Log.log)
[Client Player Log.log](https://github.com/rwmt/Multiplayer/files/6920169/Client.Player.Log.log)
[Desync-01.zip](https://github.com/rwmt/Multiplayer/files/6920170/Desync-01.zip)

**Comment by LuzBun** [comment]
Pinpointed the issue to one of my own mods, looking into it now. Issue may arise with other mods however.

**Comment by LuzBun** [comment]
Further testing has shows its MPCompat trying and failing to patch, Prison Labour, Vanilla Weapons Expanded, Simple Sidearms, Vanilla Expanded Power, and a personal mod.

Seems to only be the ones MPCompat is erroring out on. (I'd move this issue there but ya'll check the issues here more anyway ^-^)

**Comment by MistressMia** [comment]
Re-adding the personal mod, with the lines from the said mod that were erroring out in the log removed worked fine. The bug seems to be happening purely with things erroring in the log. 

Said personal mod patches a few things, one of which came from a mod that wasn't in use. Removing the related lines cleared the errors from our mod, and ceased the ticking error.

any red errors generated in the log for a patch failing brings about the Ticking error.

**Comment by LuzBun** [comment]
Fixed by aee3eeb and beyond.
