### ISSUE TITLE
Children growth moment choices not synced

### ISSUE THREAD

**Issue by megastruktur** [rwmt/Multiplayer#310]
**Version**: 1.4.3525 rev1007
**Mod**: Biotech
**Description**:
Children sync issue. 3 "parents" (players), one child. When **child grows up**, players can select skills and traits. Every player had his own random traits list, could select independently and the child for each player seemed to have picked traits selected by player. After reconnecting to the game child has the properties selected by **host**.

**Comment by SokyranTheDragon** [comment]
I've dropped 1.4 and Biotech from title, as it was a little redundant (since we've got labels).

**Comment by SokyranTheDragon** [comment]
As for patching this, I've looked a bit into it:

- The game creates `ChoiceLetter_GrowthMoment`
- Opening the letter creates `Dialog_GrowthMomentChoices`

The issues with patching this right now is that all of our `LetterWithTimeout` syncing is made through syncing the possible choices, and auto-selecting the reject option if it's about to timeout (instead of opening it and forcing selection). However, this is a dialog that is much more complex than a handful of options, like the current ones we sync. To me it feels like auto-picking a default option won't be desirable.
