### ISSUE TITLE
Crashing on Startup or infinite black screen

### ISSUE THREAD

**Issue by j0lter** [rwmt/Multiplayer#488]
RimWorld Version:
1.5.4104

Multiplayer mod version:
0.10.5
[Player.log](https://github.com/user-attachments/files/16406380/Player.log)
[error.log](https://github.com/user-attachments/files/16406384/error.log)
[crash.dmp](https://github.com/user-attachments/files/16406387/crash.dmp)
[ModsConfig.txt](https://github.com/user-attachments/files/16406415/ModsConfig.txt)

Rimworld is crashing on startup or presenting an infinite black screen after prepatcher finishes, specifically when I add the Multiplayer mod to my modlist. Attempted complete reinstall of the game and mods but received the same results.

**Comment by Zetrith** [comment]
I might release a potential fix for this in a few days, thanks for the the report. Please check back here from time to time because this seems like an important issue and I'd like to hear if it's fixed.

If you are interested in the details, I suspect that it's Harmony patches breaking badly on some people's computers. I'll try to release a version of the mod using only Prepatcher for the patches.

One last thing, to make sure it's really not related to Prepatcher, can you upload the log file with only Harmony+Multiplayer installed? Please also enable "Options->Dev->Verbose logging" in the main menu to make the game log additional useful information if you can.

**Comment by XxBeastyxX** [comment]
*A few moments later.....*

**Comment by j0lter** [comment]
I fixed it by replacing my entire pc and reinstalling windows.
