### ISSUE TITLE
Guaranteed De-sync on speeds above x1.

### ISSUE THREAD

**Issue by ZergerZ** [rwmt/Multiplayer#75]
Test game condition:

Rimworld Version: v1.1.2610
Multiplayer Version: v0.5.0.25
Game is as Direct connect with static IP and proper port forwarding.
Internet connection was tested and no issues was detected (packet loss, latency & etc)
3 players on 3 maps with a total of 20 colonists.

If the game is set to run on a speed above normal like x2 or x3 players will start lagging in ticks  behind the host.
on x2 speed it happens after few minutes of game play (ticks are growing, but slowly), 
on x3 it is nearly instant.

~~The issue might be somewhat related to:~~
~~https://github.com/Zetrith/Multiplayer/issues/79~~
~~Or~~
~~https://github.com/Parexy/Multiplayer/issues/32~~

~~Since the host machine got AMD Ryzen Threadripper 2920X 12-Core Processor~~
~~No HW bottleneck was observed during game play session.~~
Tested the above and it seems it makes no difference on intel.

all of 3 players are on the high end HW, but both clients are on Intel based CPUs

the situation was somehow improved by removing excess of domesticated animals and cleaning up the maps from raiders bodies.

**Comment by notfood** [comment]
This is more a core RimWorld issue, the more pawns, the more computation is required. You can debug this with Dubs Performance Analyser.

The only thing you can do is cut down on the map sizes and/or number of pawns in game. Using Dubs Performance Analyser to hunt for those tick abuser mods and removing them is also a solution if you play heavily modded games.

On the MP side I'm not sure what can be do to mitigate this.

**Comment by NotherGithubAccount** [comment]
Out of curiosity: You're saying multiplayer depends on everyone processing the game at the exact same speed?

Since this is an imperfect universe with nasty things like network latency and clock drift, I'm assuming there's some sort of synchronization or maybe it's just not an exact science.

Couldn't the arbiter send out regular timestamps, turn counts, or whatever the game uses to keep track? When a client gets ahead, they could slow down or pause the simulation for a moment to get back in sync, respectively request the same from the arbiter if they're ahead.

That would still leave a chance for a desync if a player makes a change affecting something another player had already calculated, but this window could be kept very small making it unlikely at least.

**Comment by LuzBun** [comment]
Not much can be done about Rimworld's single threaded nature, however it won't be the cause of desyncs themself. Ticks behind will just cause an apparent "lag" and not much else.
