### ISSUE TITLE
Pawns won't sleep while in Async mode

### ISSUE THREAD

**Issue by TheHandiCraftsman** [rwmt/Multiplayer#76]
Disclaimer - Playing with a ton of mods, 4s, 3s and lots of 0s.  But, the only way to for sure prevent the issue is by not using async.  

After some amount of time, the pawns will never elect to sleep again, and will constantly pass out exhausted.  Loading an earlier save and hosting with async off fixes.  All effected pawns get a 'canSleepTick' value in the save file.  Uneffected pawns do not have that variable set in their block.  
Setting to zero and re-hosting fixes, but it reoccurs unless async is off.  
EDIT: took out < > around canSleepTick

**Comment by Fedelaus** [comment]
I get the same issue, have spoken about it with a couple people in Discord.

![image](https://user-images.githubusercontent.com/43784056/80578917-14653980-8a01-11ea-8b0f-6ecbd0cef6b8.png)

I've asked each person for their mod list to narrow down if this is caused by a mod.

Between me and SkullOG, the following mods are common

- Pick up and Haul
- RimHUD
- Tilled Soil
- Wall Light
- Vanilla Furniture Expanded
- Prepare Carefully
- Expanded Prosthetics

Between me, SkullOG and Nexxes, the following mods are common

- RimHud
- Wall Light
- Vanilla Furniture Expanded
- Expanded Prosthetics

And then between Me, SkullOG, Nexxess and Mathoul the following mods are common

- Expanded Prosthetics

Could you confirm if you are running with Expanded Prosthetics too? I have yet to test this mod alone to see if it causes issues but it seems to be a likely culprit purely from being a common component, but I do not know much about how the mod implements its features.

**Comment by TheHandiCraftsman** [comment]
Yes I am. 
I'm using all of those mods, except Tilled Soil.  

I also saw some folks in discord being unable to draft pawns.  Different issue, but the fix is the same, and their issue is also accompanied by unexpected variables showing up for pawns in the save file.  Not sure, but could be related.

**Comment by Fedelaus** [comment]
It wasnt prepare carefully; I believe your first diagnosis being correct as I couldn't reproduce this bug with expanded prosthetics. But talking to multiple people, many who just run vanilla rimworld with Multiplayer run into this bug too.

**Comment by Gojan1** [comment]
i've encountered this issue aswel. only 2 of our colonists didnt wanna sleep, but the others all went to sleep with no issues, we did play with a-sync enabled. and i played a few days alone with those 2 colonists while my brother had his own, which the time stood still for. but they didnt have any issues.

**Comment by LuzBun** [comment]
No reports of this bug since merge (barring mods messing with it) Closed.

**Comment by StarNote1515** [comment]
seem to be have been having this problem as well now
